<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from superset/xml/schema/CRM/Superset/SupersetDashboard.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:6cf37210ed6cd996b57a6dd60911c4bc)
 */
use CRM_Superset_ExtensionUtil as E;

/**
 * Database access object for the SupersetDashboard entity.
 */
class CRM_Superset_DAO_SupersetDashboard extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_superset_dashboard';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique SupersetDashboard ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Title of the dashboard as displayed to users
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $title;

  /**
   * External dashboard ID used to embed in applications
   *
   * @var string
   *   (SQL type: varchar(50))
   *   Note that values will be retrieved from the database as a string.
   */
  public $embed_id;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_superset_dashboard';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Superset Dashboards') : E::ts('Superset Dashboard');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique SupersetDashboard ID'),
          'required' => TRUE,
          'where' => 'civicrm_superset_dashboard.id',
          'table_name' => 'civicrm_superset_dashboard',
          'entity' => 'SupersetDashboard',
          'bao' => 'CRM_Superset_DAO_SupersetDashboard',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'title' => [
          'name' => 'title',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Title'),
          'description' => E::ts('Title of the dashboard as displayed to users'),
          'required' => FALSE,
          'where' => 'civicrm_superset_dashboard.title',
          'table_name' => 'civicrm_superset_dashboard',
          'entity' => 'SupersetDashboard',
          'bao' => 'CRM_Superset_DAO_SupersetDashboard',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
        'embed_id' => [
          'name' => 'embed_id',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Embed ID'),
          'description' => E::ts('External dashboard ID used to embed in applications'),
          'required' => TRUE,
          'where' => 'civicrm_superset_dashboard.embed_id',
          'table_name' => 'civicrm_superset_dashboard',
          'entity' => 'SupersetDashboard',
          'bao' => 'CRM_Superset_DAO_SupersetDashboard',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'superset_dashboard', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'superset_dashboard', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
